baseURL = "https://idreamshen.github.io/"
languageCode = "zh-cn"
title = "ChenHsingYu"
theme = "yinyang"
googleAnalytics = "UA-49492756-1"

# Chroma Syntax Highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
    headTitle = "ChenHsingYu"
    mainSections = ["posts"]
    extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-49492756-1"></script><script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag("js", new Date());gtag("config", "UA-49492756-1");</script>'
    [[params.socials]]
    name = "Github"
    link = "https://github.com/idreamshen"
    [[params.socials]]
    name = "Email"
    link = "mailto:idream.shen@gmail.com"
