baseURL = "https://idreamshen.github.io/"
languageCode = "zh-cn"
title = "ChenHsingYu"
theme = "yinyang"
googleAnalytics = "UA-49492756-1"

# Chroma Syntax Highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
    headTitle = "ChenHsingYu"
    mainSections = ["posts"]
    [[params.socials]]
    name = "Github"
    link = "https://github.com/idreamshen"
